<?php
/**
 * Страница "Содержание".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Медигалерея</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Модуль предназначен для управления компонентами  медиагалереи на сайте. Компонент медиагалереи
        представлен в виде плагина (фотоальбом, видеоальбом, слайдер и др.) веб-приложения GearMagic.
    </p>

    <h2>Содержание:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('grid') ?>">Список компонентов медиагалереи</a></li>
    </ul>
</article>